services:
  # database:
  #   provider:
  #     type: aws-compose-service
  #     options:
  #       service: rds
  #       region: ap-southeast-1
  #       name: mydbinstance
  #       engine: postgres
  #       engine_version: "13.4"
  #       instance_class: db.t3.micro
  #       allocated_storage: 20
  #       username: admin
  #       password: password123
  #       subnet_ids:
  #         - subnet-0bb1c79de3EXAMPLE
  #         - subnet-064f5c1e2fEXAMPLE
  #       security_group_ids:
  #         - sg-0a1b2c3d4e5f6g78h
  s3:
    provider:
      type: aws-compose-service
      options:
        service: s3
        region: ap-southeast-1

  app:
    image: alpine:3.22.2
    depends_on:
      - s3
    command: ["sh", "-c", "env | sort && sleep 3600"]
